# This file handles production deployments triggered by GitHub releases
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Production
'on':
  release:
    types: [published]

permissions:
  checks: write
  contents: read

jobs:
  build_and_deploy_production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build
        run: npm run build:simple
      - name: Deploy to Firebase Production
        run: |
          npm install -g firebase-tools
          # Create a firebase.json file for production deployment
          echo '{
            "hosting": {
              "public": "build",
              "ignore": [
                "firebase.json",
                "**/.*",
                "**/node_modules/**"
              ],
              "rewrites": [
                {
                  "source": "**",
                  "destination": "/index.html"
                }
              ]
            }
          }' > firebase.json
          # Deploy to production site
          firebase deploy --only hosting --project prodable-react-page --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive
