# Firebase Deployment Workflow
# Handles staging deployment

name: Deploy to Staging
on:
  push:
    branches:
      - main

jobs:
  deploy_staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build:simple

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: |
          firebase experiments:enable webframeworks
          firebase deploy --only hosting:staging-prodable-react-page --token "${{ secrets.FIREBASE_TOKEN }}" --project prodable-react-page --non-interactive
