# Firebase Deployment Workflow
# Handles both staging and production deployments

name: Firebase Deployment
'on':
  # Deploy to staging for PRs and pushes to main
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  # Deploy to production only for releases
  release:
    types: [published]
  # Allow manual workflow runs
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  # Deploy to staging for PRs and pushes to main
  deploy_to_staging:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build
        run: npm run build:simple
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN }}'
          projectId: prodable-react-page
          target: staging-prodable-react-page
          channelId: live
      - name: Comment on PR with staging URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Deployed to staging: https://staging-prodable-react-page.web.app'
            })

  # Deploy to production only for releases
  deploy_to_production:
    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build
        run: npm run build:simple
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN }}'
          projectId: prodable-react-page
          target: prodable-react-page
          channelId: live
